spec:
  rules:
    - host: rajasekhartech.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-website-service
                port:
                  number: 80