spec:
  rules:
  - host: rajasekhar.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-2048
            port:
              number: 80